/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppLayoutRouteImport } from './routes/app/_layout'
import { Route as AppLayoutUsersRouteImport } from './routes/app/_layout.users'
import { Route as AppLayoutTemplatesRouteImport } from './routes/app/_layout.templates'
import { Route as AppLayoutSummaryRouteImport } from './routes/app/_layout.summary'
import { Route as AppLayoutSendRouteImport } from './routes/app/_layout.send'
import { Route as AppLayoutScheduleRouteImport } from './routes/app/_layout.schedule'
import { Route as AppLayoutImportRouteImport } from './routes/app/_layout.import'
import { Route as AppLayoutGroupsRouteImport } from './routes/app/_layout.groups'
import { Route as AppLayoutContactsRouteImport } from './routes/app/_layout.contacts'
import { Route as AppLayoutBillingRouteImport } from './routes/app/_layout.billing'
import { Route as AppLayoutTemplatesIndexRouteImport } from './routes/app/_layout.templates.index'
import { Route as AppLayoutSendIndexRouteImport } from './routes/app/_layout.send.index'
import { Route as AppLayoutScheduleIndexRouteImport } from './routes/app/_layout.schedule.index'
import { Route as AppLayoutImportIndexRouteImport } from './routes/app/_layout.import.index'
import { Route as AppLayoutContactsIndexRouteImport } from './routes/app/_layout.contacts.index'
import { Route as AppLayoutTemplatesTemplateIdRouteImport } from './routes/app/_layout.templates.$templateId'
import { Route as AppLayoutScheduleMsgIdRouteImport } from './routes/app/_layout.schedule.$msgId'
import { Route as AppLayoutGroupsGroupIdRouteImport } from './routes/app/_layout.groups.$groupId'
import { Route as AppLayoutContactsContactIdRouteImport } from './routes/app/_layout.contacts.$contactId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutRoute = AppLayoutRouteImport.update({
  id: '/app/_layout',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLayoutUsersRoute = AppLayoutUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutTemplatesRoute = AppLayoutTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSummaryRoute = AppLayoutSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutSendRoute = AppLayoutSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutScheduleRoute = AppLayoutScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutImportRoute = AppLayoutImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutGroupsRoute = AppLayoutGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutContactsRoute = AppLayoutContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutBillingRoute = AppLayoutBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppLayoutRoute,
} as any)
const AppLayoutTemplatesIndexRoute = AppLayoutTemplatesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutTemplatesRoute,
} as any)
const AppLayoutSendIndexRoute = AppLayoutSendIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutSendRoute,
} as any)
const AppLayoutScheduleIndexRoute = AppLayoutScheduleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutScheduleRoute,
} as any)
const AppLayoutImportIndexRoute = AppLayoutImportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutImportRoute,
} as any)
const AppLayoutContactsIndexRoute = AppLayoutContactsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppLayoutContactsRoute,
} as any)
const AppLayoutTemplatesTemplateIdRoute =
  AppLayoutTemplatesTemplateIdRouteImport.update({
    id: '/$templateId',
    path: '/$templateId',
    getParentRoute: () => AppLayoutTemplatesRoute,
  } as any)
const AppLayoutScheduleMsgIdRoute = AppLayoutScheduleMsgIdRouteImport.update({
  id: '/$msgId',
  path: '/$msgId',
  getParentRoute: () => AppLayoutScheduleRoute,
} as any)
const AppLayoutGroupsGroupIdRoute = AppLayoutGroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => AppLayoutGroupsRoute,
} as any)
const AppLayoutContactsContactIdRoute =
  AppLayoutContactsContactIdRouteImport.update({
    id: '/$contactId',
    path: '/$contactId',
    getParentRoute: () => AppLayoutContactsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/app/billing': typeof AppLayoutBillingRoute
  '/app/contacts': typeof AppLayoutContactsRouteWithChildren
  '/app/groups': typeof AppLayoutGroupsRouteWithChildren
  '/app/import': typeof AppLayoutImportRouteWithChildren
  '/app/schedule': typeof AppLayoutScheduleRouteWithChildren
  '/app/send': typeof AppLayoutSendRouteWithChildren
  '/app/summary': typeof AppLayoutSummaryRoute
  '/app/templates': typeof AppLayoutTemplatesRouteWithChildren
  '/app/users': typeof AppLayoutUsersRoute
  '/app/contacts/$contactId': typeof AppLayoutContactsContactIdRoute
  '/app/groups/$groupId': typeof AppLayoutGroupsGroupIdRoute
  '/app/schedule/$msgId': typeof AppLayoutScheduleMsgIdRoute
  '/app/templates/$templateId': typeof AppLayoutTemplatesTemplateIdRoute
  '/app/contacts/': typeof AppLayoutContactsIndexRoute
  '/app/import/': typeof AppLayoutImportIndexRoute
  '/app/schedule/': typeof AppLayoutScheduleIndexRoute
  '/app/send/': typeof AppLayoutSendIndexRoute
  '/app/templates/': typeof AppLayoutTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppLayoutRouteWithChildren
  '/app/billing': typeof AppLayoutBillingRoute
  '/app/groups': typeof AppLayoutGroupsRouteWithChildren
  '/app/summary': typeof AppLayoutSummaryRoute
  '/app/users': typeof AppLayoutUsersRoute
  '/app/contacts/$contactId': typeof AppLayoutContactsContactIdRoute
  '/app/groups/$groupId': typeof AppLayoutGroupsGroupIdRoute
  '/app/schedule/$msgId': typeof AppLayoutScheduleMsgIdRoute
  '/app/templates/$templateId': typeof AppLayoutTemplatesTemplateIdRoute
  '/app/contacts': typeof AppLayoutContactsIndexRoute
  '/app/import': typeof AppLayoutImportIndexRoute
  '/app/schedule': typeof AppLayoutScheduleIndexRoute
  '/app/send': typeof AppLayoutSendIndexRoute
  '/app/templates': typeof AppLayoutTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app/_layout': typeof AppLayoutRouteWithChildren
  '/app/_layout/billing': typeof AppLayoutBillingRoute
  '/app/_layout/contacts': typeof AppLayoutContactsRouteWithChildren
  '/app/_layout/groups': typeof AppLayoutGroupsRouteWithChildren
  '/app/_layout/import': typeof AppLayoutImportRouteWithChildren
  '/app/_layout/schedule': typeof AppLayoutScheduleRouteWithChildren
  '/app/_layout/send': typeof AppLayoutSendRouteWithChildren
  '/app/_layout/summary': typeof AppLayoutSummaryRoute
  '/app/_layout/templates': typeof AppLayoutTemplatesRouteWithChildren
  '/app/_layout/users': typeof AppLayoutUsersRoute
  '/app/_layout/contacts/$contactId': typeof AppLayoutContactsContactIdRoute
  '/app/_layout/groups/$groupId': typeof AppLayoutGroupsGroupIdRoute
  '/app/_layout/schedule/$msgId': typeof AppLayoutScheduleMsgIdRoute
  '/app/_layout/templates/$templateId': typeof AppLayoutTemplatesTemplateIdRoute
  '/app/_layout/contacts/': typeof AppLayoutContactsIndexRoute
  '/app/_layout/import/': typeof AppLayoutImportIndexRoute
  '/app/_layout/schedule/': typeof AppLayoutScheduleIndexRoute
  '/app/_layout/send/': typeof AppLayoutSendIndexRoute
  '/app/_layout/templates/': typeof AppLayoutTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/app/billing'
    | '/app/contacts'
    | '/app/groups'
    | '/app/import'
    | '/app/schedule'
    | '/app/send'
    | '/app/summary'
    | '/app/templates'
    | '/app/users'
    | '/app/contacts/$contactId'
    | '/app/groups/$groupId'
    | '/app/schedule/$msgId'
    | '/app/templates/$templateId'
    | '/app/contacts/'
    | '/app/import/'
    | '/app/schedule/'
    | '/app/send/'
    | '/app/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/app/billing'
    | '/app/groups'
    | '/app/summary'
    | '/app/users'
    | '/app/contacts/$contactId'
    | '/app/groups/$groupId'
    | '/app/schedule/$msgId'
    | '/app/templates/$templateId'
    | '/app/contacts'
    | '/app/import'
    | '/app/schedule'
    | '/app/send'
    | '/app/templates'
  id:
    | '__root__'
    | '/'
    | '/app/_layout'
    | '/app/_layout/billing'
    | '/app/_layout/contacts'
    | '/app/_layout/groups'
    | '/app/_layout/import'
    | '/app/_layout/schedule'
    | '/app/_layout/send'
    | '/app/_layout/summary'
    | '/app/_layout/templates'
    | '/app/_layout/users'
    | '/app/_layout/contacts/$contactId'
    | '/app/_layout/groups/$groupId'
    | '/app/_layout/schedule/$msgId'
    | '/app/_layout/templates/$templateId'
    | '/app/_layout/contacts/'
    | '/app/_layout/import/'
    | '/app/_layout/schedule/'
    | '/app/_layout/send/'
    | '/app/_layout/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppLayoutRoute: typeof AppLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout': {
      id: '/app/_layout'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_layout/users': {
      id: '/app/_layout/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppLayoutUsersRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/templates': {
      id: '/app/_layout/templates'
      path: '/templates'
      fullPath: '/app/templates'
      preLoaderRoute: typeof AppLayoutTemplatesRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/summary': {
      id: '/app/_layout/summary'
      path: '/summary'
      fullPath: '/app/summary'
      preLoaderRoute: typeof AppLayoutSummaryRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/send': {
      id: '/app/_layout/send'
      path: '/send'
      fullPath: '/app/send'
      preLoaderRoute: typeof AppLayoutSendRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/schedule': {
      id: '/app/_layout/schedule'
      path: '/schedule'
      fullPath: '/app/schedule'
      preLoaderRoute: typeof AppLayoutScheduleRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/import': {
      id: '/app/_layout/import'
      path: '/import'
      fullPath: '/app/import'
      preLoaderRoute: typeof AppLayoutImportRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/groups': {
      id: '/app/_layout/groups'
      path: '/groups'
      fullPath: '/app/groups'
      preLoaderRoute: typeof AppLayoutGroupsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/contacts': {
      id: '/app/_layout/contacts'
      path: '/contacts'
      fullPath: '/app/contacts'
      preLoaderRoute: typeof AppLayoutContactsRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/billing': {
      id: '/app/_layout/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppLayoutBillingRouteImport
      parentRoute: typeof AppLayoutRoute
    }
    '/app/_layout/templates/': {
      id: '/app/_layout/templates/'
      path: '/'
      fullPath: '/app/templates/'
      preLoaderRoute: typeof AppLayoutTemplatesIndexRouteImport
      parentRoute: typeof AppLayoutTemplatesRoute
    }
    '/app/_layout/send/': {
      id: '/app/_layout/send/'
      path: '/'
      fullPath: '/app/send/'
      preLoaderRoute: typeof AppLayoutSendIndexRouteImport
      parentRoute: typeof AppLayoutSendRoute
    }
    '/app/_layout/schedule/': {
      id: '/app/_layout/schedule/'
      path: '/'
      fullPath: '/app/schedule/'
      preLoaderRoute: typeof AppLayoutScheduleIndexRouteImport
      parentRoute: typeof AppLayoutScheduleRoute
    }
    '/app/_layout/import/': {
      id: '/app/_layout/import/'
      path: '/'
      fullPath: '/app/import/'
      preLoaderRoute: typeof AppLayoutImportIndexRouteImport
      parentRoute: typeof AppLayoutImportRoute
    }
    '/app/_layout/contacts/': {
      id: '/app/_layout/contacts/'
      path: '/'
      fullPath: '/app/contacts/'
      preLoaderRoute: typeof AppLayoutContactsIndexRouteImport
      parentRoute: typeof AppLayoutContactsRoute
    }
    '/app/_layout/templates/$templateId': {
      id: '/app/_layout/templates/$templateId'
      path: '/$templateId'
      fullPath: '/app/templates/$templateId'
      preLoaderRoute: typeof AppLayoutTemplatesTemplateIdRouteImport
      parentRoute: typeof AppLayoutTemplatesRoute
    }
    '/app/_layout/schedule/$msgId': {
      id: '/app/_layout/schedule/$msgId'
      path: '/$msgId'
      fullPath: '/app/schedule/$msgId'
      preLoaderRoute: typeof AppLayoutScheduleMsgIdRouteImport
      parentRoute: typeof AppLayoutScheduleRoute
    }
    '/app/_layout/groups/$groupId': {
      id: '/app/_layout/groups/$groupId'
      path: '/$groupId'
      fullPath: '/app/groups/$groupId'
      preLoaderRoute: typeof AppLayoutGroupsGroupIdRouteImport
      parentRoute: typeof AppLayoutGroupsRoute
    }
    '/app/_layout/contacts/$contactId': {
      id: '/app/_layout/contacts/$contactId'
      path: '/$contactId'
      fullPath: '/app/contacts/$contactId'
      preLoaderRoute: typeof AppLayoutContactsContactIdRouteImport
      parentRoute: typeof AppLayoutContactsRoute
    }
  }
}

interface AppLayoutContactsRouteChildren {
  AppLayoutContactsContactIdRoute: typeof AppLayoutContactsContactIdRoute
  AppLayoutContactsIndexRoute: typeof AppLayoutContactsIndexRoute
}

const AppLayoutContactsRouteChildren: AppLayoutContactsRouteChildren = {
  AppLayoutContactsContactIdRoute: AppLayoutContactsContactIdRoute,
  AppLayoutContactsIndexRoute: AppLayoutContactsIndexRoute,
}

const AppLayoutContactsRouteWithChildren =
  AppLayoutContactsRoute._addFileChildren(AppLayoutContactsRouteChildren)

interface AppLayoutGroupsRouteChildren {
  AppLayoutGroupsGroupIdRoute: typeof AppLayoutGroupsGroupIdRoute
}

const AppLayoutGroupsRouteChildren: AppLayoutGroupsRouteChildren = {
  AppLayoutGroupsGroupIdRoute: AppLayoutGroupsGroupIdRoute,
}

const AppLayoutGroupsRouteWithChildren = AppLayoutGroupsRoute._addFileChildren(
  AppLayoutGroupsRouteChildren,
)

interface AppLayoutImportRouteChildren {
  AppLayoutImportIndexRoute: typeof AppLayoutImportIndexRoute
}

const AppLayoutImportRouteChildren: AppLayoutImportRouteChildren = {
  AppLayoutImportIndexRoute: AppLayoutImportIndexRoute,
}

const AppLayoutImportRouteWithChildren = AppLayoutImportRoute._addFileChildren(
  AppLayoutImportRouteChildren,
)

interface AppLayoutScheduleRouteChildren {
  AppLayoutScheduleMsgIdRoute: typeof AppLayoutScheduleMsgIdRoute
  AppLayoutScheduleIndexRoute: typeof AppLayoutScheduleIndexRoute
}

const AppLayoutScheduleRouteChildren: AppLayoutScheduleRouteChildren = {
  AppLayoutScheduleMsgIdRoute: AppLayoutScheduleMsgIdRoute,
  AppLayoutScheduleIndexRoute: AppLayoutScheduleIndexRoute,
}

const AppLayoutScheduleRouteWithChildren =
  AppLayoutScheduleRoute._addFileChildren(AppLayoutScheduleRouteChildren)

interface AppLayoutSendRouteChildren {
  AppLayoutSendIndexRoute: typeof AppLayoutSendIndexRoute
}

const AppLayoutSendRouteChildren: AppLayoutSendRouteChildren = {
  AppLayoutSendIndexRoute: AppLayoutSendIndexRoute,
}

const AppLayoutSendRouteWithChildren = AppLayoutSendRoute._addFileChildren(
  AppLayoutSendRouteChildren,
)

interface AppLayoutTemplatesRouteChildren {
  AppLayoutTemplatesTemplateIdRoute: typeof AppLayoutTemplatesTemplateIdRoute
  AppLayoutTemplatesIndexRoute: typeof AppLayoutTemplatesIndexRoute
}

const AppLayoutTemplatesRouteChildren: AppLayoutTemplatesRouteChildren = {
  AppLayoutTemplatesTemplateIdRoute: AppLayoutTemplatesTemplateIdRoute,
  AppLayoutTemplatesIndexRoute: AppLayoutTemplatesIndexRoute,
}

const AppLayoutTemplatesRouteWithChildren =
  AppLayoutTemplatesRoute._addFileChildren(AppLayoutTemplatesRouteChildren)

interface AppLayoutRouteChildren {
  AppLayoutBillingRoute: typeof AppLayoutBillingRoute
  AppLayoutContactsRoute: typeof AppLayoutContactsRouteWithChildren
  AppLayoutGroupsRoute: typeof AppLayoutGroupsRouteWithChildren
  AppLayoutImportRoute: typeof AppLayoutImportRouteWithChildren
  AppLayoutScheduleRoute: typeof AppLayoutScheduleRouteWithChildren
  AppLayoutSendRoute: typeof AppLayoutSendRouteWithChildren
  AppLayoutSummaryRoute: typeof AppLayoutSummaryRoute
  AppLayoutTemplatesRoute: typeof AppLayoutTemplatesRouteWithChildren
  AppLayoutUsersRoute: typeof AppLayoutUsersRoute
}

const AppLayoutRouteChildren: AppLayoutRouteChildren = {
  AppLayoutBillingRoute: AppLayoutBillingRoute,
  AppLayoutContactsRoute: AppLayoutContactsRouteWithChildren,
  AppLayoutGroupsRoute: AppLayoutGroupsRouteWithChildren,
  AppLayoutImportRoute: AppLayoutImportRouteWithChildren,
  AppLayoutScheduleRoute: AppLayoutScheduleRouteWithChildren,
  AppLayoutSendRoute: AppLayoutSendRouteWithChildren,
  AppLayoutSummaryRoute: AppLayoutSummaryRoute,
  AppLayoutTemplatesRoute: AppLayoutTemplatesRouteWithChildren,
  AppLayoutUsersRoute: AppLayoutUsersRoute,
}

const AppLayoutRouteWithChildren = AppLayoutRoute._addFileChildren(
  AppLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppLayoutRoute: AppLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
