# Generated by Django 6.0.3 on 2026-03-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_credittransaction_manual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='delivered_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='failure_category',
            field=models.CharField(blank=True, choices=[('network_error', 'Network Error'), ('provider_timeout', 'Provider Timeout'), ('rate_limited', 'Rate Limited'), ('server_error', 'Server Error'), ('unknown_transient', 'Unknown Transient'), ('invalid_number', 'Invalid Number'), ('opt_out', 'Recipient Opted Out'), ('blacklisted', 'Number Blacklisted'), ('unroutable', 'Unroutable Number'), ('content_rejected', 'Content Rejected'), ('account_error', 'Provider Account Error'), ('unknown_permanent', 'Unknown Permanent')], max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='max_retries',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='schedule',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='retry_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('sent', 'Sent'), ('retrying', 'Retrying'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['status', 'scheduled_time'], name='schedule_status_time_idx'),
        ),
    ]
