# Generated by Django 6.0.3 on 2026-03-17 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_schedule_retry_delivery_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='billing_mode',
            field=models.CharField(choices=[('trial', 'Trial'), ('subscribed', 'Subscribed'), ('past_due', 'Past Due')], default='trial', max_length=20),
        ),
    ]
