# Generated by Django 6.0.3 on 2026-04-07 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_organisation_billing_past_due'),
    ]

    operations = [
    ]
