# Generated by Django 6.0.4 on 2026-05-11 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_credittransaction_unit_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='alphanumeric_sender',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
