# Generated by Django 6.0.4 on 2026-06-12 05:25

import django.db.models.deletion
from django.db import migrations, models


def link_legacy_refunds(apps, schema_editor):
    """Backfill refunded_transaction on pre-existing REFUND rows.

    Each legacy refund is linked to the most recent earlier DEDUCT/USAGE charge
    for the same org+schedule that is not already linked, so refund_usage()'s
    per-charge idempotency sees historical charges as already refunded.
    """
    CreditTransaction = apps.get_model('app', 'CreditTransaction')
    refunds = CreditTransaction.objects.filter(
        transaction_type='refund',
        refunded_transaction__isnull=True,
        schedule__isnull=False,
    ).order_by('created_at')

    for refund in refunds.iterator():
        charge = CreditTransaction.objects.filter(
            organisation_id=refund.organisation_id,
            schedule_id=refund.schedule_id,
            transaction_type__in=['deduct', 'usage'],
            created_at__lte=refund.created_at,
            refund__isnull=True,
        ).order_by('-created_at').first()
        if charge:
            refund.refunded_transaction = charge
            refund.save(update_fields=['refunded_transaction'])


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_trial_to_prepaid_add_credit_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='credittransaction',
            name='refunded_transaction',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='app.credittransaction'),
        ),
        migrations.RunPython(link_legacy_refunds, migrations.RunPython.noop),
    ]
