# Generated by Django 6.0.4 on 2026-06-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_credittransaction_refunded_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='past_due_source',
            field=models.CharField(blank=True, choices=[('clerk', 'Clerk subscription'), ('stripe_invoice', 'Stripe invoice')], max_length=20, null=True),
        ),
    ]
