# Generated by Django 6.0.4 on 2026-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_organisation_past_due_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='dispatch_attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
