# Generated by Django 6.0.4 on 2026-06-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_schedule_dispatch_attempted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'webhook_events',
                'constraints': [models.UniqueConstraint(fields=('provider', 'event_id'), name='uniq_webhook_provider_event')],
            },
        ),
    ]
