# Generated by Django 6.0.4 on 2026-06-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_webhook_event_dedup'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='billing_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
