# Generated by Django 6.0.4 on 2026-06-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_organisation_billing_event_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['organisation', 'status', '-scheduled_time'], name='schedule_org_status_desc'),
        ),
    ]
