# Generated by Django 6.0.4 on 2026-07-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_schedule_org_status_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='callback_registered',
            field=models.BooleanField(default=False),
        ),
    ]
