# Generated by Django 6.0.4 on 2026-07-17 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_schedule_callback_registered'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='two_way',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='InboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('broadcast_id', models.CharField(db_index=True, max_length=255)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('received_at', models.DateTimeField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_opt_out', models.BooleanField(default=False)),
                ('dedup_key', models.CharField(max_length=64, unique=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.contact')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.organisation')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages_read', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_messages', to='app.schedule')),
            ],
            options={
                'db_table': 'inbound_messages',
                'indexes': [models.Index(fields=['organisation', 'contact', '-received_at'], name='inbound_org_contact_desc'), models.Index(condition=models.Q(('read_at__isnull', True)), fields=['organisation'], name='inbound_unread_partial')],
            },
        ),
    ]
